<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>Assets\Vish_Logo_Multiple.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Data\config.json" />
      <Content Include="Data\config.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Serilog" Version="4.4.1-dev-02443" />
      <PackageReference Include="Serilog.Sinks.File" Version="8.0.0-nblumhardt-02322" />
      <PackageReference Include="SSH.NET" Version="2025.1.0" />
    </ItemGroup>

    <ItemGroup>
      <Resource Include="Assets\FileNotFound.png" />
      <Resource Include="Assets\Vish_Logo_Multiple.ico" />
    </ItemGroup>

    <ItemGroup>
      <Page Update="View\UserControls\MainWindow\BottomBar.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="View\UserControls\MainWindow\MenuBar.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="View\UserControls\MainWindow\Overview.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="View\UserControls\MainWindow\StatusBar.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="View\UserControls\CustomTextInput.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

    <ItemGroup>
      <None Include="PythonScripts\*.py">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Content Include="PythonRuntime\**\*">
          <Link>Python\%(RecursiveDir)%(Filename)%(Extension)</Link>
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
</Project>
