name: Build VisH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: VisH
          environment-file: VisH/PythonScripts/environment.yml
          auto-activate-base: false
          auto-activate: true

      - name: Test Python environment
        shell: powershell
        run: |
          python -c "import rdkit, cclib, numpy, scipy, pandas, matplotlib, PIL, reportlab; print('Alle Pakete OK')"
          
      - name: Install conda-pack
        shell: powershell
        run: |
          python -m pip install conda-pack

      - name: Pack Python environment
        shell: powershell
        run: |
          conda-pack -n VisH -o python-runtime.tar.gz
          
      - name: Extract Python runtime
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force publish\Python | Out-Null
          tar -xzf python-runtime.tar.gz -C publish\Python

      - name: Build VisH
        run: dotnet publish VisH/VisH.csproj -c Release -r win-x64 --self-contained true -o publish
        
      - name: Verify publish directory
        shell: powershell
        run: |
          Write-Host "VisH:"
          Test-Path publish\VisH.exe

          Write-Host "Python:"
          Test-Path publish\Python\python.exe

          Write-Host "Python scripts:"
          Test-Path publish\PythonScripts\SmilesValidation.py
          
      - name: Install Inno Setup
        shell: powershell
        run: |
          choco install innosetup -y --no-progress
          
      - name: Build installer
        shell: powershell
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "VisH\installer\VisH.iss"
          
      